import Link from "next/link";
import "./globals.css";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogOutBtn from "./LogOutBtn";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);

  return (
    <html lang="ko">
      <body>
        <div className="navbar">
          <div className="navbar">
            <Link href="/" className="logo">
              Apple forum
            </Link>
            <Link href="/list">List</Link>
            {session ? (
              <span>
                <Link href={`/user/${session.user.email}`}>
                  {session.user.name}님
                </Link>
                <LogOutBtn />
              </span>
            ) : (
              <span>
                <LoginBtn />
                <button>
                  <Link href="/register">회원가입</Link>
                </button>
              </span>
            )}
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
